import {
  useEffect,
  useState,
} from "react";

import {
  BellRing,
  CloudRain,
  RefreshCw,
  ShieldAlert,
  TriangleAlert,
} from "lucide-react";

import toast from "react-hot-toast";

import {
  getClimateAlerts,
} from "../services/api";

export function Alerts() {
  const [
    alerts,
    setAlerts,
  ] = useState([]);

  const [
    loading,
    setLoading,
  ] = useState(true);

  async function loadAlerts() {
    setLoading(true);

    try {
      const data =
        await getClimateAlerts(
          30
        );

      setAlerts(
        data.alerts || []
      );
    } catch (error) {
      console.error(error);

      toast.error(
        "Unable to load climate alerts."
      );
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    loadAlerts();
  }, []);

  return (
    <div className="page">
      <section className="page-heading page-heading-row">
        <div>
          <span className="eyebrow">
            CLIMATE MONITORING
          </span>

          <h1>
            Climate Alerts
          </h1>

          <p>
            Recent high-risk hazard
            signals generated by the
            climate intelligence layer.
          </p>
        </div>

        <button
          className="button button-secondary"
          onClick={loadAlerts}
          disabled={loading}
        >
          <RefreshCw
            size={16}
            className={
              loading
                ? "spin"
                : ""
            }
          />
          Refresh
        </button>
      </section>

      {alerts.length === 0 &&
      !loading ? (
        <div className="empty-state">
          <div className="empty-icon">
            <BellRing size={25} />
          </div>

          <h2>
            No active climate alerts
          </h2>

          <p>
            High-risk predictions
            generated by the existing
            ML engine will appear here.
          </p>
        </div>
      ) : (
        <div className="alerts-list">
          {alerts.map(
            (alert) => (
              <AlertCard
                key={
                  alert.id ||
                  alert._id
                }
                alert={alert}
              />
            )
          )}
        </div>
      )}
    </div>
  );
}

function AlertCard({
  alert,
}) {
  const severity =
    String(
      alert.severity ||
        "medium"
    ).toLowerCase();

  const icon =
    alert.hazardType ===
    "heavy_rainfall" ? (
      <CloudRain size={21} />
    ) : severity ===
      "critical" ||
      severity ===
        "high" ? (
      <TriangleAlert
        size={21}
      />
    ) : (
      <ShieldAlert
        size={21}
      />
    );

  return (
    <article
      className={`alert-card alert-${severity}`}
    >
      <div className="alert-icon">
        {icon}
      </div>

      <div className="alert-content">
        <div className="alert-topline">
          <span className="alert-type">
            {String(
              alert.hazardType ||
                "climate"
            )
              .replaceAll(
                "_",
                " "
              )
              .toUpperCase()}
          </span>

          <span className="alert-time">
            {alert.createdAt
              ? new Date(
                  alert.createdAt
                ).toLocaleString()
              : "Recent"}
          </span>
        </div>

        <h2>
          {alert.title}
        </h2>

        <p>
          {alert.message}
        </p>

        <div className="alert-meta">
          <span>
            Severity:{" "}
            {severity}
          </span>

          {alert.riskPercentage !=
            null && (
            <span>
              Risk:{" "}
              {Number(
                alert.riskPercentage
              ).toFixed(0)}
              %
            </span>
          )}

          {alert.latitude !=
            null &&
            alert.longitude !=
              null && (
              <span>
                Location:{" "}
                {Number(
                  alert.latitude
                ).toFixed(3)}
                ,{" "}
                {Number(
                  alert.longitude
                ).toFixed(3)}
              </span>
            )}
        </div>
      </div>
    </article>
  );
}